src/Entity/Forecast.php
<?php

namespace App\Entity;

use App\Repository\ForecastRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ForecastRepository::class)]
class Forecast
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'forecasts')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Location $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 3, scale: '0')]
    private ?string $temperature = null;

    #[ORM\Column(length: 50)]
    private ?string $cloud = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 4, scale: '0')]
    private ?string $atmospheric_pressure = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getTemperature(): ?string
    {
        return $this->temperature;
    }

    public function setTemperature(string $temperature): static
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getCloud(): ?string
    {
        return $this->cloud;
    }

    public function setCloud(string $cloud): static
    {
        $this->cloud = $cloud;

        return $this;
    }

    public function getAtmosphericPressure(): ?string
    {
        return $this->atmospheric_pressure;
    }

    public function setAtmosphericPressure(string $atmospheric_pressure): static
    {
        $this->atmospheric_pressure = $atmospheric_pressure;

        return $this;
    }

    public function getFahrenheit(): ?string
    {
        return $this->temperature * 9 / 5 + 32;
    }
}

src/Form/ForecastType.php
<?php

namespace App\Form;

use App\Entity\Forecast;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class ForecastType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateType::class)
            ->add('temperature', NumberType::class, [
                'attr' => [
                    'min' => -50,
                    'max' => 50,
                ],
                'html5' => true,
            ])
            ->add('cloud', TextType::class, [
                'attr' => [
                    'placeholder' => 'Cloud',
                    'minLength' => 3,
                ],
            ])
            ->add('atmospheric_pressure', NumberType::class, [
                'attr' => [
                    'min' => 800,
                    'max' => 1100,
                ],
                'html5' => true,
            ])
            ->add('location', EntityType::class, [
                'class' => 'App\Entity\Location',
                'choice_label' => 'city',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Forecast::class,
        ]);
    }
}

src/Controller/ForecastController.php
<?php

namespace App\Controller;

use App\Entity\Forecast;
use App\Form\ForecastType;
use App\Repository\ForecastRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/forecast')]
class ForecastController extends AbstractController
{
    #[Route('/', name: 'app_forecast_index', methods: ['GET'])]
    #[IsGranted('ROLE_FORECAST_INDEX')]
    public function index(ForecastRepository $forecastRepository): Response
    {
        return $this->render('forecast/index.html.twig', [
            'forecasts' => $forecastRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_forecast_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FORECAST_NEW')]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $forecast = new Forecast();
        $form = $this->createForm(ForecastType::class, $forecast, [
            'validation_groups' => 'create',
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($forecast);
            $entityManager->flush();

            return $this->redirectToRoute('app_forecast_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forecast/new.html.twig', [
            'forecast' => $forecast,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_forecast_show', methods: ['GET'])]
    #[IsGranted('ROLE_FORECAST_SHOW')]
    public function show(Forecast $forecast): Response
    {
        return $this->render('forecast/show.html.twig', [
            'forecast' => $forecast,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_forecast_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_FORECAST_EDIT')]
    public function edit(Request $request, Forecast $forecast, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ForecastType::class, $forecast);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_forecast_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('forecast/edit.html.twig', [
            'forecast' => $forecast,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_forecast_delete', methods: ['POST'])]
    #[IsGranted('ROLE_FORECAST_DELETE')]
    public function delete(Request $request, Forecast $forecast, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$forecast->getId(), $request->request->get('_token'))) {
            $entityManager->remove($forecast);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_forecast_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/forecast/_delete_form.html.twig
<form method="post" action="{{ path('app_forecast_delete', {'id': forecast.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ forecast.id) }}">
    <button class="btn btn-outline-danger">Delete</button>
</form>

templates/forecast/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/forecast/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Forecast{% endblock %}

{% block body %}
    <h1>Edit Forecast</h1>

    {{ include('forecast/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-outline-info" href="{{ path('app_forecast_index') }}" role="button">back to list</a>

    {{ include('forecast/_delete_form.html.twig') }}
{% endblock %}

templates/forecast/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forecast index{% endblock %}

{% block body %}
    <h1>Forecast index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Temperature</th>
                <th>Cloud</th>
                <th>Atmospheric_pressure</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for forecast in forecasts %}
            <tr>
                <td>{{ forecast.id }}</td>
                <td>{{ forecast.date ? forecast.date|date('Y-m-d') : '' }}</td>
                <td>{{ forecast.temperature }}</td>
                <td>{{ forecast.cloud }}</td>
                <td>{{ forecast.atmosphericPressure }}</td>
                <td>
                    {%  if is_granted('ROLE_FORECAST_SHOW') %}
                    <a class="btn btn-outline-info" href="{{ path('app_forecast_show', {'id': forecast.id}) }}" role="button">show</a>
                    {% endif %}
                    {%  if is_granted('ROLE_FORECAST_EDIT') %}
                    <a class="btn btn-outline-dark" href="{{ path('app_forecast_edit', {'id': forecast.id}) }}" role="button">edit</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% if is_granted('ROLE_FORECAST_NEW') %}
    <a class="btn btn-outline-success" href="{{ path('app_forecast_new') }}" role="button">Create new</a>
    {% endif %}
{% endblock %}

templates/forecast/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Forecast{% endblock %}

{% block body %}
    <h1>Create new Forecast</h1>

    {{ include('forecast/_form.html.twig') }}

    <a class="btn btn-outline-info" href="{{ path('app_forecast_index') }}" role="button">back to list</a>
{% endblock %}

templates/forecast/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Forecast{% endblock %}

{% block body %}
    <h1>Forecast</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ forecast.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ forecast.date ? forecast.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ forecast.temperature }}</td>
            </tr>
            <tr>
                <th>Cloud</th>
                <td>{{ forecast.cloud }}</td>
            </tr>
            <tr>
                <th>Atmospheric_pressure</th>
                <td>{{ forecast.atmosphericPressure }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-outline-info" href="{{ path('app_forecast_index') }}" role="button">back to list</a>

    <a class="btn btn-outline-dark" href="{{ path('app_forecast_edit', {'id': forecast.id}) }}" role="button">edit</a>

    {{ include('forecast/_delete_form.html.twig') }}
{% endblock %}